# Generated by Django 3.1.3 on 2020-11-28 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='club_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название клуба'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='website_url',
            field=models.URLField(blank=True, null=True, verbose_name='Адрес вебсайта'),
        ),
    ]
