# Generated by Django 3.1.3 on 2020-12-11 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20201128_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about_club',
            field=models.TextField(blank=True, null=True, verbose_name='О клубе'),
        ),
    ]
