# Generated by Django 3.1.3 on 2020-12-11 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_about_club'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tg_username',
        ),
    ]
