# Generated by Django 3.1.3 on 2021-01-20 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_contacts'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='club_is_active',
            field=models.BooleanField(default=False, verbose_name='Клуб активен'),
        ),
    ]
