# Generated by Django 3.1.3 on 2020-11-11 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('other', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agegroup',
            name='name',
        ),
    ]
