# Generated by Django 3.1.3 on 2020-11-10 19:12

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Заявка на бронирование',
                'verbose_name_plural': 'Заявки на бронирование',
            },
        ),
        migrations.CreateModel(
            name='PartnerFeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Имя')),
                ('company_name', models.CharField(max_length=256, null=True, verbose_name='Название компании')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='e-mail')),
                ('mobile_phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None, verbose_name='Мобильный телефон')),
            ],
            options={
                'verbose_name': 'Заявки на партнерство',
                'verbose_name_plural': 'Заявки на партнерство',
            },
        ),
        migrations.CreateModel(
            name='CourseBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_bookings', to='applications.bookingapplication', verbose_name='Заявка на бронирование')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_bookings', to='main.course', verbose_name='Курс')),
                ('lesson_times', models.ManyToManyField(related_name='course_bookings', to='main.LessonTime', verbose_name='Время занятий')),
            ],
            options={
                'verbose_name': 'Бронирование курса',
                'verbose_name_plural': 'Бронирования курсов',
            },
        ),
    ]
