# Generated by Django 3.1.3 on 2020-12-11 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20201212_0128'),
        ('applications', '0005_auto_20201117_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingapplication',
            name='is_processed',
            field=models.BooleanField(blank=True, default=False, verbose_name='Обработано'),
        ),
        migrations.AddField(
            model_name='coursebooking',
            name='lesson_times_confirmed',
            field=models.ManyToManyField(related_name='course_bookings_confirmed', to='main.LessonTime', verbose_name='Время занятий подтвержденные партнером'),
        ),
        migrations.AddField(
            model_name='partnershipapplication',
            name='is_processed',
            field=models.BooleanField(blank=True, default=False, verbose_name='Обработано'),
        ),
    ]
