# Generated by Django 3.1.3 on 2021-01-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20201212_0128'),
        ('applications', '0006_auto_20201212_0157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursebooking',
            name='lesson_times',
            field=models.ManyToManyField(blank=True, related_name='course_bookings', to='main.LessonTime', verbose_name='Время занятий'),
        ),
        migrations.AlterField(
            model_name='coursebooking',
            name='lesson_times_confirmed',
            field=models.ManyToManyField(blank=True, related_name='course_bookings_confirmed', to='main.LessonTime', verbose_name='Время занятий подтвержденные партнером'),
        ),
    ]
