version: '3'
services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db
    ports:
      - "5432:5432"
  web:
    build: .
    command: sh -c "/wait &&
      pip install -r requirements.txt &&
      python manage.py migrate &&
      python manage.py runserver 0:8990"
    volumes:
      - .:/uniclub_mobile
    ports:
      - "8990:8990"
    depends_on:
      - db
    links:
      - db
    env_file:
    - ./.env.dev

volumes:
  postgres_data:
  rabbit: