version: '3'
services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db
    ports:
      - "5433:5432"
  web:
    build: .
    command: sh -c "/wait &&
      pip install -r requirements.txt &&
      python manage.py migrate &&
      python manage.py collectstatic --no-input --clear &&
      python manage.py runserver 0:8990"
#      gunicorn uniclub_mobile.wsgi:application --bind 0.0.0.0:8990"
    volumes:
      - .:/uniclub_mobile
    ports:
      - "8990:8990"
    depends_on:
      - db
      - rabbit
    links:
      - db
    env_file:
    - ./.env.prod

volumes:
  postgres_data:
  static_volume:
  media_volume:
  rabbit: