# Generated by Django 3.1.3 on 2020-11-10 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('other', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('administrative_division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='other.administrativedivision', verbose_name='Административное деление')),
                ('age_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='other.agegroup', verbose_name='Возрастная группа')),
                ('attendance_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='other.attendancetype', verbose_name='Вид посещения')),
                ('grade_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='other.gradetypegroup', verbose_name='Группа занятий')),
                ('grade_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='other.gradetype', verbose_name='Вид занятия')),
            ],
            options={
                'verbose_name': 'Занятие',
                'verbose_name_plural': 'Занятия',
            },
        ),
        migrations.CreateModel(
            name='LessonTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели')),
                ('from_time', models.TimeField(verbose_name='От')),
                ('to_time', models.TimeField(verbose_name='До')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_times', to='main.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'Время занятия',
                'verbose_name_plural': 'Время занятий',
                'ordering': ['weekday', 'from_time', 'to_time'],
            },
        ),
    ]
