# Generated by Django 3.1.3 on 2020-11-11 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessontime',
            name='course',
        ),
        migrations.CreateModel(
            name='WeekDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveSmallIntegerField(choices=[(0, 'Понедельник'), (1, 'Вторник'), (2, 'Среда'), (3, 'Четверг'), (4, 'Пятница'), (5, 'Суббота'), (6, 'Воскресенье')], verbose_name='День недели')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weekdays', to='main.course', verbose_name='Курс')),
            ],
            options={
                'verbose_name': 'День недели',
                'verbose_name_plural': 'Дни недели',
                'ordering': ['day'],
            },
        ),
        migrations.AlterField(
            model_name='lessontime',
            name='weekday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_times', to='main.weekday', verbose_name='День недели'),
        ),
    ]
