# Generated by Django 3.1.3 on 2020-11-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201111_1501'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='age_group',
        ),
        migrations.AddField(
            model_name='course',
            name='from_age',
            field=models.PositiveSmallIntegerField(default=None, verbose_name='Возраст от', null=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='to_age',
            field=models.PositiveSmallIntegerField(default=None, verbose_name='Возраст до', null=True),
            preserve_default=False,
        ),
    ]
