# Generated by Django 3.1.3 on 2020-11-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_courseimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseimage',
            options={'verbose_name': 'Фото курса', 'verbose_name_plural': 'Фото курсов'},
        ),
        migrations.AddField(
            model_name='courseimage',
            name='image',
            field=models.ImageField(null=True, upload_to='course_images/', verbose_name='Изображение'),
        ),
    ]
