# Generated by Django 3.1.3 on 2020-12-03 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201204_0304'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursereview',
            options={'ordering': ['-created_at']},
        ),
    ]
