# Generated by Django 3.1.3 on 2020-12-04 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20201204_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursereview',
            name='is_anonymous',
            field=models.BooleanField(default=False, verbose_name='Анонимно'),
        ),
    ]
