# Generated by Django 3.1.3 on 2020-12-11 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_coursereview_is_anonymous'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursereview',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AddField(
            model_name='course',
            name='short_description',
            field=models.CharField(max_length=100, null=True, verbose_name='Краткое описание'),
        ),
    ]
