# Generated by Django 3.1.3 on 2021-03-06 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_course_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='is_top',
            field=models.BooleanField(default=False, verbose_name='Топ'),
        ),
    ]
